name: AI PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures full Git history

      - name: Verify Branches
        run: git branch -a # Debugging step to check available branches

      - name: Fetch Main Branch
        run: |
          git fetch origin main || echo "Main branch not found, skipping"
          git checkout main || echo "Already on main or main not found"

      - name: Fetch PR Changes
        run: |
          if git rev-parse origin/main >/dev/null 2>&1; then
            git diff origin/main..HEAD > pr_changes.diff
          else
            echo "No main branch found, using HEAD" > pr_changes.diff
          fi

      - name: Review PR with OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          RESPONSE=$(curl -s -X POST "https://api.openai.com/v1/chat/completions" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "gpt-4",
              "messages": [
                {"role": "system", "content": "You are a senior software engineer reviewing pull requests for a TypeScript/Node.js project. Analyze the changes and suggest improvements."},
                {"role": "user", "content": "Please review this PR and provide suggestions:\n\n'"$(cat pr_changes.diff)"'"}
              ]
            }')

          echo "### AI Review Feedback" > review_comment.md
          echo "$RESPONSE" | jq -r '.choices[0].message.content' >> review_comment.md

      - name: Post AI Review Comment
        uses: mshick/add-pr-comment@v2
        with:
          message-path: review_comment.md
