name: AI PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write # Ensures GITHUB_TOKEN can comment on PRs

jobs:
  ai-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures full Git history is available

      - name: Fetch PR Base Branch
        run: |
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          echo "Fetching base branch: $BASE_BRANCH"
          git fetch origin "$BASE_BRANCH:$BASE_BRANCH"

      - name: Fetch PR Changes
        run: |
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          DIFF_FILE="pr_changes.diff"

          echo "Generating diff from $BASE_BRANCH to HEAD..."
          git diff --unified=0 "$BASE_BRANCH"...HEAD | head -n 500 > "$DIFF_FILE"

          echo "---- Generated Diff (First 500 Lines) ----"
          cat "$DIFF_FILE"
          echo "------------------------------------------"

      - name: Review PR with OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          DIFF_FILE="pr_changes.diff"
          DIFF_CONTENT=$(cat "$DIFF_FILE")

          # Debug: Print the diff content before sending to OpenAI
          echo "---- DIFF CONTENT BEFORE SENDING ----"
          echo "$DIFF_CONTENT"
          echo "-------------------------------------"

          # Handle cases where diff is empty
          if [ -z "$DIFF_CONTENT" ]; then
            echo "LGTM ✅" > review_comment.md
            exit 0
          fi

          # OpenAI API request
          RESPONSE=$(curl -s -X POST "https://api.openai.com/v1/chat/completions" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d "$(jq -Rs --arg model "gpt-3.5-turbo-1106" \
            --arg system_msg "You are a senior software engineer reviewing a pull request. Analyze the changes, identify issues, and suggest improvements." \
            --arg user_msg "Review this pull request and provide structured feedback:\n\n\($DIFF_CONTENT)" \
            '{
              model: $model,
              messages: [
                {role: "system", content: $system_msg},
                {role: "user", content: $user_msg}
              ]
            }')")

          echo "---- RAW OPENAI RESPONSE ----"
          echo "$RESPONSE"
          echo "----------------------------"

          REVIEW_TEXT=$(echo "$RESPONSE" | jq -r '.choices[0].message.content')

          # Ensure AI response is meaningful; fallback to a warning
          echo "### AI Review Feedback" > review_comment.md
          if [ -z "$REVIEW_TEXT" ] || [ "$REVIEW_TEXT" == "null" ]; then
            echo "❗ AI Review Failed: OpenAI returned no feedback. Check API response in logs." >> review_comment.md
          else
            echo "$REVIEW_TEXT" >> review_comment.md
          fi

      - name: Post AI Review Comment
        uses: mshick/add-pr-comment@v2
        with:
          message-path: review_comment.md
          repo-token: ${{ secrets.GITHUB_TOKEN }} # Uses GitHub's built-in token
