name: AI PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures full Git history is available

      - name: Verify Available Branches
        run: git branch -a # Debugging step to show which branches exist

      - name: Fetch Default Branch (main)
        run: |
          # Fetch the 'main' branch from origin.
          # If your repo uses 'master' instead of 'main', change accordingly.
          if git ls-remote --exit-code --heads origin main; then
            git fetch origin main
          else
            echo "The 'main' branch does not exist. Exiting..."
            exit 1
          fi

      - name: Fetch PR Changes
        run: |
          # Ensure that origin/main exists before running diff.
          if git rev-parse origin/main >/dev/null 2>&1; then
            # Use the double-dot syntax to compare the current HEAD against origin/main.
            git diff origin/main..HEAD > pr_changes.diff
          else
            echo "No 'main' branch found, so no diff is available." > pr_changes.diff
          fi

      - name: Review PR with OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          RESPONSE=$(curl -s -X POST "https://api.openai.com/v1/chat/completions" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "gpt-4",
              "messages": [
                {"role": "system", "content": "You are a senior software engineer reviewing pull requests for a TypeScript/Node.js project. Analyze the changes and suggest improvements."},
                {"role": "user", "content": "Please review this PR and provide suggestions:\n\n'"$(cat pr_changes.diff)"'"}
              ]
            }')

          echo "### AI Review Feedback" > review_comment.md
          echo "$RESPONSE" | jq -r '.choices[0].message.content' >> review_comment.md

      - name: Post AI Review Comment
        uses: mshick/add-pr-comment@v2
        with:
          message-path: review_comment.md
