name: Publish to npm

on:
  push:
    tags:
      - "v*" # Runs only when a version tag (e.g., v1.0.0) is pushed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org/"

      - name: Install Dependencies
        run: npm ci

      - name: Ensure Rollup is Installed
        run: npm install --save-dev rollup @rollup/rollup-linux-x64-gnu

      - name: Build the Package
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
